#  Copyright 2017-2020 bmcustodio
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.255.0/24
      driver: default
services:
  host_a:
    command:
      - "--debug"
      - "--name=host_a"
      - "--cluster_name=C1"
      - "--cluster=nats://0.0.0.0:6222"
      - "--http_port=8222"
      - "--routes=nats-route://host_b:6222,nats-route://host_c:6222"
      - "--js"
    image: "nats:latest"
    networks:
      - main
    ports:
      - "14222:4222"
      - "18222:8222"
  host_b:
    command:
      - "--debug"
      - "--name=host_b"
      - "--cluster_name=C1"
      - "--cluster=nats://0.0.0.0:6222"
      - "--http_port=8222"
      - "--routes=nats-route://host_a:6222,nats-route://host_c:6222"
      - "--js"
    image: "nats:latest"
    networks:
      - main
    ports:
      - "24222:4222"
      - "28222:8222"
  host_c:
    command:
      - "--debug"
      - "--name=host_c"
      - "--cluster_name=C1"
      - "--cluster=nats://0.0.0.0:6222"
      - "--http_port=8222"
      - "--routes=nats-route://host_a:6222,nats-route://host_b:6222"
      - "--js"
    image: "nats:latest"
    networks:
      - main
    ports:
      - "34222:4222"
      - "38222:8222"
version: "3.7"
