version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  dbtest:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    volumes:
      - "/etc/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php"
    environment:
      - PMA_HOST=127.0.0.1:3306
    networks:
      - db-network

  activemq:
    image: rmohr/activemq
    ports:
      - "8161:8161"
      - "61613:61613"
      
networks:
  db-network:
