version: '3'
services:
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  db:
    # image: mysql:5.7
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - db-network

  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    networks:
      - db-network

  #cache:
  #  image: redis:6.2-alpine
  #  # restart: always
  #  ports:
  #    - '6379:6379'
      # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      # volumes: 
      # - cache:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8111:80 #volumes:
      #      - "/etc/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php"
      #environment:
      #- PMA_HOST=127.0.0.1:3306
    depends_on:
      - db
    networks:
      - db-network
  # nats:
  #   image: nats:latest
  #   command: ["--config", "/nats-server.conf", "--js"]
  #   ports:
  #     - 4222:4222
  #     - 6222:6222
  #     - 8222:8222



  #activemq:
  #  image: rmohr/activemq
  #  ports:
  #    - "8161:8161"
  #    - "61613:61613"

networks:
  db-network:
